spring.application.name=springrecipe

spring.datasource.url=jdbc:postgresql://localhost:5432/recipeSystem_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.com.example.springrecipe=DEBUG
logging.level.com.example.springrecipe.service=INFO
logging.level.com.example.springrecipe.repository=DEBUG
logging.level.com.example.springrecipe.controller=INFO
logging.level.com.example.springrecipe.aspect=DEBUG

# Tomcat
server.tomcat.threads.max=1500
server.tomcat.threads.min-spare=300
server.tomcat.accept-count=3000
server.tomcat.max-connections=15000
server.tomcat.connection-timeout=120000
server.tomcat.keep-alive-timeout=120000
server.tomcat.max-keep-alive-requests=100

# HikariCP
spring.datasource.hikari.maximum-pool-size=300
spring.datasource.hikari.minimum-idle=50
spring.datasource.hikari.connection-timeout=60000

spring.task.execution.pool.core-size=200
spring.task.execution.pool.max-size=1000
spring.task.execution.pool.queue-capacity=10000

logging.level.org.springframework=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=com.example.springrecipe.controller
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha